# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goldo/table.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from goldo.common import geometry_pb2 as goldo_dot_common_dot_geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='goldo/table.proto',
  package='goldo.table',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11goldo/table.proto\x12\x0bgoldo.table\x1a\x1bgoldo/common/geometry.proto\"s\n\x04\x43\x61ke\x12\n\n\x02id\x18\x01 \x01(\r\x12*\n\x04pose\x18\x02 \x01(\x0b\x32\x1c.goldo.common.geometry.Point\x12%\n\x05\x63olor\x18\x03 \x01(\x0e\x32\x16.goldo.table.CakeColor\x12\x0c\n\x04here\x18\x04 \x01(\x08\".\n\nTableState\x12 \n\x05\x63\x61kes\x18\x01 \x03(\x0b\x32\x11.goldo.table.Cake*c\n\tCakeColor\x12\x11\n\rCOLOR_UNKNOWN\x10\x00\x12\x0f\n\x0b\x43OLOR_BROWN\x10\x01\x12\x10\n\x0c\x43OLOR_YELLOW\x10\x02\x12\x0e\n\nCOLOR_PINK\x10\x03\x12\x10\n\x0c\x43OLOR_RECIPE\x10\x04\x62\x06proto3'
  ,
  dependencies=[goldo_dot_common_dot_geometry__pb2.DESCRIPTOR,])

_CAKECOLOR = _descriptor.EnumDescriptor(
  name='CakeColor',
  full_name='goldo.table.CakeColor',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COLOR_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COLOR_BROWN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COLOR_YELLOW', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COLOR_PINK', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COLOR_RECIPE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=228,
  serialized_end=327,
)
_sym_db.RegisterEnumDescriptor(_CAKECOLOR)

CakeColor = enum_type_wrapper.EnumTypeWrapper(_CAKECOLOR)
COLOR_UNKNOWN = 0
COLOR_BROWN = 1
COLOR_YELLOW = 2
COLOR_PINK = 3
COLOR_RECIPE = 4



_CAKE = _descriptor.Descriptor(
  name='Cake',
  full_name='goldo.table.Cake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='goldo.table.Cake.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pose', full_name='goldo.table.Cake.pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='goldo.table.Cake.color', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='here', full_name='goldo.table.Cake.here', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=178,
)


_TABLESTATE = _descriptor.Descriptor(
  name='TableState',
  full_name='goldo.table.TableState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cakes', full_name='goldo.table.TableState.cakes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=226,
)

_CAKE.fields_by_name['pose'].message_type = goldo_dot_common_dot_geometry__pb2._POINT
_CAKE.fields_by_name['color'].enum_type = _CAKECOLOR
_TABLESTATE.fields_by_name['cakes'].message_type = _CAKE
DESCRIPTOR.message_types_by_name['Cake'] = _CAKE
DESCRIPTOR.message_types_by_name['TableState'] = _TABLESTATE
DESCRIPTOR.enum_types_by_name['CakeColor'] = _CAKECOLOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Cake = _reflection.GeneratedProtocolMessageType('Cake', (_message.Message,), {
  'DESCRIPTOR' : _CAKE,
  '__module__' : 'goldo.table_pb2'
  # @@protoc_insertion_point(class_scope:goldo.table.Cake)
  })
_sym_db.RegisterMessage(Cake)

TableState = _reflection.GeneratedProtocolMessageType('TableState', (_message.Message,), {
  'DESCRIPTOR' : _TABLESTATE,
  '__module__' : 'goldo.table_pb2'
  # @@protoc_insertion_point(class_scope:goldo.table.TableState)
  })
_sym_db.RegisterMessage(TableState)


# @@protoc_insertion_point(module_scope)
